baseURL = 'https://swhl.github.io/RapidVideOCR/'
languageCode = 'en-us'
title = 'RapidVideOCR Documentation'
enableEmoji = true
enableGitInfo = true # N.B. .GitInfo does not currently function with submodule content directories
# googleAnalytics = "G-VXQVVP7V8K" # (or set via env variable HUGO_GOOGLEANALYTICS)

[build]
  noJSConfigInAssets = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
    [markup.tableOfContents]
      endLevel = 6
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]

  # Google Fonts
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font

    [params.footer]
        copyright = "© :YEAR: SWHL. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
        version   = true # include git commit info in footer

    [params.social]
        github = "SWHL/RapidVideOCR" # github.com/YOUR_GITHUB_ID
        twitter = "_SWHL"            # twitter.com/YOUR_TWITTER_ID
        # instagram = "colinwilson"      # instagram.com/YOUR_INSTAGRAM_ID
        # rss = true                     # show rss icon with link

    [params.docs] # Parameters for the /docs 'template'
        title           = "RapidVideOCR Documentation"                        # default html title for documentation pages/sections

        prismTheme = "twilight"

        # pathName        = "docs"                            # path for documentation site | default "docs"

        # themeColor      = "cyan"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = true                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        # gitinfo
        repoURL         = "https://github.com/SWHL/RapidVideOCR"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
        repoBranch      = "main"                              # Name of your Git repository branch
        editPage        = true                                # enable 'Edit this page' feature - default false
        lastMod         = true                                # enable 'Last modified' date on pages - default false
        lastModRelative = true                                # format 'Last modified' time as relative - default true

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # icons
        sidebarIcons    = true                                # enable sidebar icons? default false
        titleIcon       = false                                # enable front matter icon title prfefix? default is false

        # content navigation
        breadcrumbs     = true                                # default is true
        navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description
        backToTop       = true                                # enable back-to-top button? default true

        # front matter
        descriptions    = true                                # enable front matter descriptions under content title?

        intLinkTooltip   = true # Enable a tooltip for internal links that displays info about the destination? default false

    [params.flexsearch] # Parameters for FlexSearch
        enabled             = true
        tokenize            = "full"
        optimize            = true
        cache               = 100
        minQueryChar        = 1 # default is 0 (disabled)
        maxResult           = 5 # default is 5
        searchSectionsIndex = []

    [params.docsearch] # Parameters for DocSearch
        # appID     = "O2QIOCBDAK"                       # Algolia Application ID (or set env variable HUGO_PARAM_DOCSEARCH_appID)
        # apiKey    = "fdc60eee76a72a35d739b54521498b77" # Algolia Search-Only API (Public) Key (or set env variable HUGO_PARAM_DOCSEARCH_apiKey)
        # indexName = "dev_lotusdocs.dev"               # Index Name to perform search on (or set env variable HUGO_PARAM_DOCSEARCH_indexName)

    [params.plausible] # Parameters for Plausible Analytics
        dataDomain = "rapidai.github.io/rapidocrdocs" # (or set via env variable HUGO_PARAMS_PLAUSIBLE_dataDomain)
        scriptURL  = "/docs/s/js/script.outbound-links.js"       # (or set via env variable HUGO_PARAMS_PLAUSIBLE_scriptURL)
        eventAPI   = "/docs/s/api/event/"       # optional - (or set via env variable HUGO_PARAMS_PLAUSIBLE_eventAPI)

    [params.feedback]
        enabled = false
        emoticonTpl = true
        eventDest = ["plausible"]
        emoticonEventName = "Feedback"
        positiveEventName = "Positive Feedback"
        negativeEventName = "Negative Feedback"
        positiveFormTitle = "What did you like?"
        negativeFormTitle = "What went wrong?"
        successMsg = "Thank you for helping to improve Lotus Docs' documentation!"
        errorMsg = "Sorry! There was an error while attempting to submit your feedback!"
        positiveForm = [
          ["Accurate", "Accurately describes the feature or option."],
          ["Solved my problem", "Helped me resolve an issue."],
          ["Easy to understand", "Easy to follow and comprehend."],
          ["Something else"]
        ]
        negativeForm = [
          ["Inaccurate", "Doesn't accurately describe the feature or option."],
          ["Couldn't find what I was looking for", "Missing important information."],
          ["Hard to understand", "Too complicated or unclear."],
          ["Code sample errors", "One or more code samples are incorrect."],
          ["Something else"]
        ]

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10

# [[menu.primary]]
#     name  = "Showcase"
#     url = "/showcase"
#     identifier = "showcase"
#     weight = 20

[[menu.primary]]
    name  = "Community"
    url = "https://github.com/SWHL/RapidVideOCR/discussions"
    identifier = "community"
    weight = 30
