# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\ProgramFiles\_self\RapidVideOCR\demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 237)
        self.label_img_dir = QtWidgets.QLabel(Dialog)
        self.label_img_dir.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_img_dir.setFont(font)
        self.label_img_dir.setObjectName("label_img_dir")
        self.le_display_img_dir = QtWidgets.QLineEdit(Dialog)
        self.le_display_img_dir.setGeometry(QtCore.QRect(100, 20, 421, 31))
        self.le_display_img_dir.setObjectName("le_display_img_dir")
        self.btn_select_img_dir = QtWidgets.QPushButton(Dialog)
        self.btn_select_img_dir.setGeometry(QtCore.QRect(540, 20, 81, 31))
        self.btn_select_img_dir.setObjectName("btn_select_img_dir")
        self.lable_save_name = QtWidgets.QLabel(Dialog)
        self.lable_save_name.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lable_save_name.setFont(font)
        self.lable_save_name.setObjectName("lable_save_name")
        self.le_save_path = QtWidgets.QLineEdit(Dialog)
        self.le_save_path.setGeometry(QtCore.QRect(100, 80, 421, 31))
        self.le_save_path.setObjectName("le_save_path")
        self.btn_save_result = QtWidgets.QPushButton(Dialog)
        self.btn_save_result.setGeometry(QtCore.QRect(540, 80, 81, 31))
        self.btn_save_result.setObjectName("btn_save_result")
        self.btn_dialog_ok_cancel = QtWidgets.QDialogButtonBox(Dialog)
        self.btn_dialog_ok_cancel.setGeometry(QtCore.QRect(410, 170, 156, 23))
        self.btn_dialog_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_dialog_ok_cancel.setObjectName("btn_dialog_ok_cancel")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(130, 150, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.label_mode = QtWidgets.QLabel(Dialog)
        self.label_mode.setGeometry(QtCore.QRect(20, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)

        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")

        self.label_batch = QtWidgets.QLabel(Dialog)
        self.label_batch.setGeometry(QtCore.QRect(20, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_batch.setFont(font)
        self.label_batch.setObjectName("label_batch")
        
        self.le_batch = QtWidgets.QLineEdit(Dialog)
        self.le_batch.setGeometry(QtCore.QRect(100, 180, 113, 20))
        self.le_batch.setObjectName("le_batch")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_img_dir.setText(_translate("Dialog", "图像目录："))
        self.btn_select_img_dir.setText(_translate("Dialog", "点击选择"))
        self.lable_save_name.setText(_translate("Dialog", "保存路径："))
        self.btn_save_result.setText(_translate("Dialog", "点击选择"))
        self.btn_dialog_ok_cancel.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.radioButton.setText(_translate("Dialog", "叠图识别"))
        self.label_mode.setText(_translate("Dialog", "是否叠图识别："))
        self.label_batch.setText(_translate("Dialog", "叠图个数："))
