name: Push rapid_videocr to pypi

on:
  push:
    # branches: [ main ]
    tags:
      - v*
    # paths:
    #   - 'rapid_videocr/**'
    #   - 'docs/doc_whl.md'
    #   - 'setup.py'
    #   - '.github/workflows/AutoPushToPypi.yml'

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Unit testings
        run: |
          pip install -r requirements.txt --break-system-packages
          pip install pytest six --break-system-packages
          pytest -s tests/test_*.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run setup.py
        run: |
          pip install wheel get_pypi_latest_version --break-system-packages

          python -m pip install --upgrade pip --break-system-packages
          python setup.py bdist_wheel ${{ github.ref_name }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
