name: Push rapid_videocr to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'rapid_videocr/**'
      - 'docs/doc_whl.md'
      - 'setup.py'
      - '.github/workflows/AutoPushToPypi.yml'

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Unit testings
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install six
          pytest tests/test_*.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run setup.py
        run: |
          pip install wheel

          python -m pip install --upgrade pip
          python setup.py bdist_wheel ${{ github.event.head_commit.message }}

      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.5.0
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/