name: Push rapid_videocr to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'rapid_videocr/**'
      - 'docs/doc_whl.md'
      - 'setup.py'
      - '.github/workflows/AutoPushToPypi.yml'

jobs:
  GenerateWHL_PushPyPi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run setup.py
        run: |
          python -m pip install --upgrade pip
          python setup.py bdist_wheel ${{ github.event.head_commit.message }}

      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.5.0
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/