name: github pages

on:
  push:
    branches:
      - hugo_source  # Set a branch that will trigger a deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/hugo_source'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public